In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.18.5


In [32]:
one_dim_array = np.array([1,2,3,4])
one_dim_array

array([1, 2, 3, 4])

In [33]:
bool_arrray = np.full((3,3),True )
bool_arrray

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [66]:
rand = np.arange(1,50,1)
rand

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
even = rand[rand%2==0] # even number
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [68]:
odd = rand[rand%2!=0] # for odd number
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [69]:
rand

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [78]:
# replace the number with the number on the specific condition
#here my conditoon replace odd number with one but its effecting 
# orginal
odd[odd%2==1]=-1
odd

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [112]:
#how to change the number on the conditon without effecting the
#orignal
number  = np.arange(10)
number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
out = np.where(number %2==1,-1,number)

print(number)
print(out)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [117]:
number.reshape(2,-1) # setting to -1 automaticallu decided number of column

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
# How to stack two array vertically?

In [138]:
a  = np.arange(12).reshape(2,-1)
print( "a :->>>",  a)
b  = np.arange(12).reshape(2,-1)
print("b  :->>>" ,b)


a :->>> [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
b  :->>> [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [140]:
np.concatenate([a,b], axis=0)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [141]:
# other way to concatenate

In [142]:
np.vstack([a,b]) #verticaly stack

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [143]:
 # how to stack two array horizantall ?

In [145]:
update_A_B = np.concatenate([a,b],axis=1)
update_A_B

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])