In [2]:
import numpy as np
import math

# Array creation

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
print(a.ndim)
print(a.shape)

1
(3,)


In [15]:
b = np.array([[23,34],[34,23]])
print(b)
print(b.ndim)

[[23 34]
 [34 23]]
2


In [17]:
b.shape

(2, 2)

In [19]:
b.dtype

dtype('int64')

In [23]:
c  = np.array([12.3,22.3,3.3,4.3,3.3,3.0])
c

array([12.3, 22.3,  3.3,  4.3,  3.3,  3. ])

In [28]:
#convert int into the float 
c = np.array([2.3,4.5,3])
print(c)

[2.3 4.5 3. ]


In [32]:
d = np.zeros([2,3])
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
e  = np.ones([2,3])
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:

#genratate the random numbers
np.random.rand(1,10)

array([[0.47554527, 0.27146135, 0.30979504, 0.77898954, 0.50155618,
        0.77072426, 0.74703585, 0.8932518 , 0.8403538 , 0.04045254]])

In [50]:
range_number = np.arange(12,50,5)
range_number

array([12, 17, 22, 27, 32, 37, 42, 47])

In [51]:
# if we want to generate a sequence of floats, we can use the linspace() function. In this function the third
# argument isn't the difference between two numbers, but the total number of items you want to generate
np.linspace( 0, 2, 15 ) # 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [57]:
float_number = np.linspace(0,5 ,5)
print(float_number , len(float_number))

[0.   1.25 2.5  3.75 5.  ] 5


# Array Operation

In [72]:
a = np.array([1,3,4,3])
b= np.array([1,2,3,4])
temp = a @ b
print(a*b )
print(a+b)
print(a-b)
print(a/b)
print(a@b)
print( "temp : " ,temp)
print("Mean of a : ",a.min())
print()
print("shape of a : ",a.shape)
print("shape of b : ",b.shape)

[ 1  6 12 12]
[2 5 7 7]
[ 0  1  1 -1]
[1.         1.5        1.33333333 0.75      ]
31
temp :  31
Mean of a :  1

shape of a :  (4,)
shape of b :  (4,)


In [63]:
# With arithmetic manipulation, we can convert current data to the way we want it to be. Here's a real-world
# problem I face - I moved down to the United States about 6 years ago from Canada. In Canada we use celcius
# for temperatures, and my wife still hasn't converted to the US system which uses farenheit. With numpy I 
# could easily convert a number of farenheit values, say the weather forecase, to ceclius

# Let's create an array of typical Ann Arbor winter farenheit values
farenheit = np.array([0,-10,-5,-15,0])

# And the formula for conversion is ((°F − 32) × 5/9 = °C)
celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])